[package]
name = "cmac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "*"
prettytable = "*"
tabled = { version = "*", features = ["color"] } 
libc = "*"
nix = "*"

